/**
 * Slyce API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: admin@slyce.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface AnalyticsEvent {
    /**
     * The action for the event. Required
     */
    eventAction?: string;
    /**
     * The general event category. Required
     */
    eventCategory?: string;
    /**
     * An optional descriptor for the event. Optional
     */
    eventLabel?: string;
    /**
     * Count of events in a sequence starting at 1. Required
     */
    hitNumber?: number;
    /**
     * The recorded time at which the event occurred. ISO 8601 format. Required
     */
    hitTimestamp?: string;
    /**
     * Optionally add custom dimensions. Optional
     */
    customDimensions?: any;
}
