/**
 * Slyce API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: admin@slyce.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * The anchor (point of interest) of the image
 */
export interface Anchor {
    /**
     * The x coordinate
     */
    x?: number;
    /**
     * The y coordinate
     */
    y?: number;
}
