/**
 * Slyce API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: admin@slyce.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ReferenceImageSize } from './referenceImageSize';


/**
 * The image data
 */
export interface Image {
    /**
     * The image id
     */
    id?: string;
    /**
     * The base64 encoded string of the image
     */
    bytes?: string;
    /**
     * The size of the image
     */
    size?: ReferenceImageSize;
}
