/**
 * Slyce API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: admin@slyce.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Coordinate } from './coordinate';


export interface InlineResponse20010Items {
    /**
     * The item value
     */
    value?: string;
    /**
     * The item confidence
     */
    confidence?: number;
    /**
     * The relative distance from the detected apparel and the anchor
     */
    anchorDistance?: number;
    /**
     * The coordinates of the match
     */
    coordinates?: Array<Coordinate>;
}
