/**
 * Slyce API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: admin@slyce.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InlineResponse2008Items } from './inlineResponse2008Items';


export interface InlineResponse2008 {
    /**
     * The response type
     */
    type?: string;
    items?: Array<InlineResponse2008Items>;
}
