/**
 * Slyce API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: admin@slyce.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InlineResponse20015Items } from './inlineResponse20015Items';


export interface InlineResponse20015 {
    /**
     * The response type
     */
    type?: string;
    items?: Array<InlineResponse20015Items>;
    /**
     * The total number of items available
     */
    totalItems?: number;
    /**
     * The cursor for paging the items
     */
    cursor?: string;
}
