/**
 * Slyce API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: admin@slyce.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SampleData } from './sampleData';


export interface NewDatasetItemDoc {
    /**
     * The items to be imported to the dataset
     */
    dataItems?: Array<SampleData>;
    /**
     * The language code of the items, in iso-alpha-2 format. Defaults to 'en'
     */
    languageCode?: string;
    /**
     * The country codes of the items, in iso-alpha-2 format. If then data items are for any country leave empty.
     */
    countryCodes?: Array<string>;
    /**
     * A flag indicating if any previously imported images associated with these data items should be reprocessed.
     */
    force?: boolean;
}
