/**
 * Slyce API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: admin@slyce.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface NewDatasetDoc {
    /**
     * The type of the dataset.
     */
    datasetType: string;
    /**
     * The name of the dataset.
     */
    name: string;
    /**
     * The keys of the fields containing image_urls for the dataset.
     */
    imageUrlKeys?: Array<string>;
    /**
     * The keys of the fields containing searchable data for the dataset.
     */
    searchableKeys?: Array<string>;
    /**
     * The keys of the fields containing facetable data for the dataset.
     */
    facetableKeys?: Array<string>;
    /**
     * The name of another dataset from which settings and items should be copied (if necessary).
     */
    copyFrom?: string;
}
