/**
 * Slyce API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: admin@slyce.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface NewExternalDatasetDoc {
    /**
     * The name of the dataset.
     */
    name: string;
    /**
     * The base url for the dataset
     */
    baseUrl: string;
    /**
     * The request parameters
     */
    request?: any;
    /**
     * The object to transfroms the response from the api call.
     */
    returns: string;
    /**
     * The keys of the fields containing facetable data for the dataset.
     */
    facetableKeys?: Array<string>;
    /**
     * The key and values for facetable_keys
     */
    facetValues?: string;
}
