/**
 * Slyce API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: admin@slyce.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ProcessStatusDoc } from './processStatusDoc';


export interface NewJobDoc {
    /**
     * ???
     */
    topic?: string;
    /**
     * The type of message
     */
    msgType?: string;
    /**
     * The account id related to the job
     */
    accountId?: string;
    /**
     * The task id
     */
    taskId?: string;
    /**
     * Task created by
     */
    createdBy?: string;
    /**
     * The job id
     */
    jobId?: string;
    /**
     * The name of the job
     */
    name?: string;
    processStatus?: ProcessStatusDoc;
}
