/**
 * Slyce API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: admin@slyce.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface NewReferenceDatasetDoc {
    /**
     * The type of the dataset.
     */
    datasetType: string;
    /**
     * The name of the reference dataset.
     */
    name: string;
    /**
     * The name of another dataset from which settings and items should be copied (if necessary).
     */
    copyFrom?: string;
}
