/**
 * Slyce API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: admin@slyce.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface PatchAPIKeyDoc {
    /**
     * The name of the API key
     */
    name: string;
    /**
     * null
     */
    spaceIds?: Array<string>;
    /**
     * The access control list as an object with the operation as the key and the permission status as a boolean
     */
    acl?: any;
}
