/**
 * Slyce API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: admin@slyce.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Coordinate } from './coordinate';
import { ReferenceImageMatchValue } from './referenceImageMatchValue';


export interface ReferenceImageMatch {
    /**
     * The value associated with the match
     */
    value?: ReferenceImageMatchValue;
    /**
     * The confidence of the match
     */
    confidence?: number;
    /**
     * The coordinates of the match
     */
    coordinates?: Array<Coordinate>;
    /**
     * The distance from the anchor
     */
    anchorDistance?: number;
}
