/**
 * Slyce API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: admin@slyce.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * The value associated with the match
 */
export interface ReferenceImageMatchValue {
    /**
     * The id of the dataset containing the match
     */
    datasetId?: number;
    /**
     * The ids of the items in the dataset
     */
    itemIds?: Array<string>;
}
