/**
 * Slyce API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: admin@slyce.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface UpdateLensDoc {
    /**
     * optional to update the name of the lens. Do not include to leave the same
     */
    lensName?: string;
    /**
     * optional to update the capture mode of the lens. Do not include to leave the same
     */
    captureMode?: string;
    /**
     * optional to update the local detectors of the lens. Do not include to leave the same
     */
    localDetectors?: Array<string>;
    /**
     * optional to update the template of the lens. Do not include to leave the same
     */
    template?: string;
    /**
     * optional to update the workflow of the lens. Do not include to leave the same
     */
    workflowId?: string;
}
