/**
 * Slyce API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: admin@slyce.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface UpdateWorkflowDoc {
    /**
     * The name of the workflow
     */
    workflowName?: string;
    /**
     * The combination of operations and operators
     */
    workflowWeldStatement?: string;
    /**
     * The ISO 639-1 Code of the language to use throughout the workflow
     */
    workflowLanguage: string;
    /**
     * The ISO 639-1 alpha-2 Code of the language to use throughout the workflow
     */
    workflowLanguageCode?: string;
    /**
     * The ISO 3166-1 alpha-2 Code of the country to use throughout the workflow
     */
    workflowCountryCode?: string;
}
