/**
 * Slyce API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: admin@slyce.it
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface WorkflowDoc {
    /**
     * The timestamp the item was created
     */
    createdAt?: Date;
    /**
     * The user that created the item
     */
    createdBy?: string;
    /**
     * The timestamp the item was last updated
     */
    updatedAt?: Date;
    /**
     * The user that last updated the item
     */
    updatedBy?: string;
    /**
     * The id of the workflow
     */
    id?: string;
    /**
     * The name of the workflow
     */
    name?: string;
    /**
     * The combination of operations and operators
     */
    weldStatement?: string;
    /**
     * The ISO 639-1 alpha-2 Code of the language to use throughout the workflow
     */
    languageCode?: string;
    /**
     * The ISO 3166-1 alpha-2 Code of the country to use throughout the workflow
     */
    countryCode?: string;
}
